name: flutter_poster_maker
description: A production-ready poster editing widget/app using Flutter and GetX.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

  # QR Code
  qr_flutter: ^4.1.0

  # UUID
  uuid: ^4.2.1

  # Image picker
  image_picker: ^1.0.7

  # PDF export
  pdf: ^3.10.7
  printing: ^5.11.1

  # File operations
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  flutter_svg:
  google_fonts:
  universal_html:
  permission_handler: ^11.3.0
  image_gallery_saver_plus: ^4.0.1
  file_selector: ^1.0.3
  device_info_plus: ^10.1.0
  flutter_colorpicker:
  
  # Image caching
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Ensure assets are declared
  assets:
    - assets/stickers/
    # - assets/images/ # If you have local images